### PR TITLE
Use test unit explicitly

### PR DESCRIPTION
**Pull request by cosmo0920**
Because Ruby 2.2 does not provide minitest with test-unit compatibility layer.

### CODE REVIEW

**Comment by y-ken** [comment]
Nice work! Thank you very match!!

**Comment by cosmo0920** [comment]
Wow, thank you for merging and quick response!

**Comment by y-ken** [comment]
Do you need to release this gem as new version soon?

**Comment by cosmo0920** [comment]
Please wait a moment.
This repository seems do more work such as secret parameters support and label feature support.

**Comment by y-ken** [comment]
Sure. I'll await of your pull-request.
Thank you.

**Comment by cosmo0920** [comment]
I've registered PRs that I said above. Please review them.

**Pull request merged**
